# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x04\x62\x61se\"\x07\n\x05\x45mpty\"\x16\n\x08\x43lientId\x12\n\n\x02id\x18\x01 \x01(\t\"<\n\x08SignalId\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\tnamespace\x18\x02 \x01(\x0b\x32\x0f.base.NameSpace\"J\n\nSignalInfo\x12\x1a\n\x02id\x18\x01 \x01(\x0b\x32\x0e.base.SignalId\x12 \n\x08metaData\x18\x02 \x01(\x0b\x32\x0e.base.MetaData\"\xcd\x01\n\x08MetaData\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0b\n\x03max\x18\x0c \x01(\x02\x12\x0b\n\x03min\x18\r \x01(\x02\x12\x0c\n\x04unit\x18\x07 \x01(\t\x12\x0c\n\x04size\x18\x08 \x01(\x05\x12\r\n\x05isRaw\x18\t \x01(\x08\x12\x0e\n\x06\x66\x61\x63tor\x18\n \x01(\x01\x12\x0e\n\x06offset\x18\x0b \x01(\x01\x12\x0e\n\x06sender\x18\x0e \x03(\t\x12\x10\n\x08receiver\x18\x0f \x03(\t\x12\x11\n\tcycleTime\x18\x10 \x01(\x02\x12\x12\n\nstartValue\x18\x11 \x01(\x02\"\x19\n\tNameSpace\x12\x0c\n\x04name\x18\x01 \x01(\t\"T\n\x0bNetworkInfo\x12\"\n\tnamespace\x18\x01 \x01(\x0b\x32\x0f.base.NameSpace\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"V\n\tFrameInfo\x12$\n\nsignalInfo\x18\x01 \x01(\x0b\x32\x10.base.SignalInfo\x12#\n\tchildInfo\x18\x02 \x03(\x0b\x32\x10.base.SignalInfo\"(\n\x06\x46rames\x12\x1e\n\x05\x66rame\x18\x01 \x03(\x0b\x32\x0f.base.FrameInfob\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_CLIENTID = DESCRIPTOR.message_types_by_name['ClientId']
_SIGNALID = DESCRIPTOR.message_types_by_name['SignalId']
_SIGNALINFO = DESCRIPTOR.message_types_by_name['SignalInfo']
_METADATA = DESCRIPTOR.message_types_by_name['MetaData']
_NAMESPACE = DESCRIPTOR.message_types_by_name['NameSpace']
_NETWORKINFO = DESCRIPTOR.message_types_by_name['NetworkInfo']
_FRAMEINFO = DESCRIPTOR.message_types_by_name['FrameInfo']
_FRAMES = DESCRIPTOR.message_types_by_name['Frames']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:base.Empty)
  })
_sym_db.RegisterMessage(Empty)

ClientId = _reflection.GeneratedProtocolMessageType('ClientId', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTID,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:base.ClientId)
  })
_sym_db.RegisterMessage(ClientId)

SignalId = _reflection.GeneratedProtocolMessageType('SignalId', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALID,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:base.SignalId)
  })
_sym_db.RegisterMessage(SignalId)

SignalInfo = _reflection.GeneratedProtocolMessageType('SignalInfo', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALINFO,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:base.SignalInfo)
  })
_sym_db.RegisterMessage(SignalInfo)

MetaData = _reflection.GeneratedProtocolMessageType('MetaData', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:base.MetaData)
  })
_sym_db.RegisterMessage(MetaData)

NameSpace = _reflection.GeneratedProtocolMessageType('NameSpace', (_message.Message,), {
  'DESCRIPTOR' : _NAMESPACE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:base.NameSpace)
  })
_sym_db.RegisterMessage(NameSpace)

NetworkInfo = _reflection.GeneratedProtocolMessageType('NetworkInfo', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKINFO,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:base.NetworkInfo)
  })
_sym_db.RegisterMessage(NetworkInfo)

FrameInfo = _reflection.GeneratedProtocolMessageType('FrameInfo', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEINFO,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:base.FrameInfo)
  })
_sym_db.RegisterMessage(FrameInfo)

Frames = _reflection.GeneratedProtocolMessageType('Frames', (_message.Message,), {
  'DESCRIPTOR' : _FRAMES,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:base.Frames)
  })
_sym_db.RegisterMessage(Frames)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=22
  _EMPTY._serialized_end=29
  _CLIENTID._serialized_start=31
  _CLIENTID._serialized_end=53
  _SIGNALID._serialized_start=55
  _SIGNALID._serialized_end=115
  _SIGNALINFO._serialized_start=117
  _SIGNALINFO._serialized_end=191
  _METADATA._serialized_start=194
  _METADATA._serialized_end=399
  _NAMESPACE._serialized_start=401
  _NAMESPACE._serialized_end=426
  _NETWORKINFO._serialized_start=428
  _NETWORKINFO._serialized_end=512
  _FRAMEINFO._serialized_start=514
  _FRAMEINFO._serialized_end=600
  _FRAMES._serialized_start=602
  _FRAMES._serialized_end=642
# @@protoc_insertion_point(module_scope)
