# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diagnostics_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64iagnostics_api.proto\x12\x04\x62\x61se\x1a\x0c\x63ommon.proto\"\x81\x01\n\x12\x44iagnosticsRequest\x12\x1e\n\x06upLink\x18\x01 \x01(\x0b\x32\x0e.base.SignalId\x12 \n\x08\x64ownLink\x18\x02 \x01(\x0b\x32\x0e.base.SignalId\x12\x11\n\tserviceId\x18\x03 \x01(\x0c\x12\x16\n\x0e\x64\x61taIdentifier\x18\x04 \x01(\x0c\"\"\n\x13\x44iagnosticsResponse\x12\x0b\n\x03raw\x18\x05 \x01(\x0c\x32\x63\n\x12\x44iagnosticsService\x12M\n\x14SendDiagnosticsQuery\x12\x18.base.DiagnosticsRequest\x1a\x19.base.DiagnosticsResponse\"\x00\x62\x06proto3')



_DIAGNOSTICSREQUEST = DESCRIPTOR.message_types_by_name['DiagnosticsRequest']
_DIAGNOSTICSRESPONSE = DESCRIPTOR.message_types_by_name['DiagnosticsResponse']
DiagnosticsRequest = _reflection.GeneratedProtocolMessageType('DiagnosticsRequest', (_message.Message,), {
  'DESCRIPTOR' : _DIAGNOSTICSREQUEST,
  '__module__' : 'diagnostics_api_pb2'
  # @@protoc_insertion_point(class_scope:base.DiagnosticsRequest)
  })
_sym_db.RegisterMessage(DiagnosticsRequest)

DiagnosticsResponse = _reflection.GeneratedProtocolMessageType('DiagnosticsResponse', (_message.Message,), {
  'DESCRIPTOR' : _DIAGNOSTICSRESPONSE,
  '__module__' : 'diagnostics_api_pb2'
  # @@protoc_insertion_point(class_scope:base.DiagnosticsResponse)
  })
_sym_db.RegisterMessage(DiagnosticsResponse)

_DIAGNOSTICSSERVICE = DESCRIPTOR.services_by_name['DiagnosticsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DIAGNOSTICSREQUEST._serialized_start=46
  _DIAGNOSTICSREQUEST._serialized_end=175
  _DIAGNOSTICSRESPONSE._serialized_start=177
  _DIAGNOSTICSRESPONSE._serialized_end=211
  _DIAGNOSTICSSERVICE._serialized_start=213
  _DIAGNOSTICSSERVICE._serialized_end=312
# @@protoc_insertion_point(module_scope)
