name: Doc builder and mypy

on: push

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docs
        env:
          NO_TTY: true
        run: |
          cd python/remotivelabs-broker
          ./docker-build.sh
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          architecture: x64
      - name: Install mypy
        run: |
          pip install mypy
          pip install python/remotivelabs-broker
          pip install python/remotivelabs-broker[default]
      - name: Run mypy
        run: |
          mypy python/remotivelabs-broker/remotivelabs/
          mypy . --exclude python/remotivelabs-broker/remotivelabs/
