name: Build remotivelabs-broker package and documentation

on: push

jobs:
  build:
    name: Build remotivelabs-broker

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build package and docs
        env:
          NO_TTY: true
        run: ./python/remotivelabs-broker/docker-build.sh
      - id: build_output
        run: echo "whl_path=$(ls python/remotivelabs-broker/dist/*.whl)" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: remotivelabs-broker-whl
          path: ${{ steps.build_output.outputs.whl_path }}
          if-no-files-found: error
          retention-days: 1
          overwrite: true

  test:
    name: Install remotivelabs-broker
    needs: build

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-22.04, ubuntu-24.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v4
        with:
          name: remotivelabs-broker-whl

      - name: Install remotivelabs-broker
        run: pip install *.whl
