name: Code-QA

on: push

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1

  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: "."
          args: format --check --diff

  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          architecture: x64
      - name: Install pylint
        run: |
          pip install pylint
          pip install python/remotivelabs-broker
          pip install python/remotivelabs-broker[default]
      - name: Run pylint
        run: |
          cd python/remotivelabs-broker
          pylint **/*.py
